INSERT INTO products (name, description, category, price, rating, reviews_count, url) VALUES
('Buty trekkingowe Mountain Pro Waterproof',
 'Wodoodporne buty trekkingowe do chodzenia po górach z membraną i antypoślizgową podeszwą.',
 'Obuwie trekkingowe',
 299.99,
 4.7,
 184,
 'https://example.com/products/1'),

('Buty outdoorowe Trail Step',
 'Lekkie buty outdoorowe przeznaczone do spacerów, szlaków i aktywności w terenie.',
 'Obuwie outdoorowe',
 229.99,
 4.4,
 97,
 'https://example.com/products/2'),

('Buty sportowe City Run',
 'Lekkie buty sportowe do codziennego chodzenia i biegania po mieście.',
 'Obuwie sportowe',
 189.99,
 4.3,
 121,
 'https://example.com/products/3'),

('Buty eleganckie Classic Leather',
 'Skórzane buty eleganckie do pracy, spotkań biznesowych i formalnych okazji.',
 'Obuwie eleganckie',
 349.99,
 4.5,
 61,
 'https://example.com/products/4'),

('Kalosze Rain Guard',
 'Wysokie kalosze chroniące przed deszczem i błotem. Dobre do pracy w ogrodzie.',
 'Obuwie gumowe',
 119.99,
 4.1,
 88,
 'https://example.com/products/5'),

('Buty zimowe Snow Trek',
 'Ciepłe buty zimowe z ociepleniem, przeznaczone do chodzenia po śniegu i niskich temperaturach.',
 'Obuwie zimowe',
 279.99,
 4.6,
 143,
 'https://example.com/products/6'),

('Buty trailowe Run Terrain',
 'Buty do biegania w terenie z dobrą przyczepnością i lekką konstrukcją.',
 'Obuwie trailowe',
 259.99,
 4.5,
 110,
 'https://example.com/products/7'),

('Sandały trekkingowe Summer Path',
 'Sandały trekkingowe do letnich spacerów i łatwych szlaków turystycznych.',
 'Sandały trekkingowe',
 159.99,
 4.2,
 74,
 'https://example.com/products/8'),

('Buty miejskie Daily Walk',
 'Wygodne buty miejskie do codziennego użytkowania i spacerów po mieście.',
 'Obuwie miejskie',
 199.99,
 4.4,
 132,
 'https://example.com/products/9'),

('Buty robocze Safety Strong',
 'Wytrzymałe buty robocze ze wzmocnionym noskiem i antypoślizgową podeszwą.',
 'Obuwie robocze',
 239.99,
 4.3,
 156,
 'https://example.com/products/10');