INSERT INTO products
(name, description, category, price, rating, reviews_count, url, color, target_gender, shoe_type, waterproof, season)
VALUES
('Buty trekkingowe Mountain Pro Waterproof',
 'Wodoodporne męskie buty trekkingowe do chodzenia po górach z membraną i antypoślizgową podeszwą.',
 'Obuwie trekkingowe',
 299.99, 4.7, 184, 'https://example.com/products/1',
 'brązowy', 'męskie', 'trekkingowe', true, 'całoroczne'),

('Buty outdoorowe Trail Step',
 'Lekkie męskie buty outdoorowe przeznaczone do spacerów, szlaków i aktywności w terenie.',
 'Obuwie outdoorowe',
 229.99, 4.4, 97, 'https://example.com/products/2',
 'czarny', 'męskie', 'outdoorowe', false, 'całoroczne'),

('Buty sportowe City Run',
 'Lekkie buty sportowe unisex do codziennego chodzenia i biegania po mieście.',
 'Obuwie sportowe',
 189.99, 4.3, 121, 'https://example.com/products/3',
 'biały', 'unisex', 'sportowe', false, 'całoroczne'),

('Buty eleganckie Classic Leather',
 'Czarne męskie skórzane buty eleganckie do pracy, spotkań biznesowych i formalnych okazji.',
 'Obuwie eleganckie',
 349.99, 4.5, 61, 'https://example.com/products/4',
 'czarny', 'męskie', 'eleganckie', false, 'całoroczne'),

('Kalosze Rain Guard',
 'Wysokie wodoodporne kalosze unisex chroniące przed deszczem i błotem. Dobre do pracy w ogrodzie.',
 'Obuwie gumowe',
 119.99, 4.1, 88, 'https://example.com/products/5',
 'zielony', 'unisex', 'kalosze', true, 'jesienne'),

('Buty zimowe Snow Trek',
 'Ciepłe męskie buty zimowe z ociepleniem, przeznaczone do chodzenia po śniegu i niskich temperaturach.',
 'Obuwie zimowe',
 279.99, 4.6, 143, 'https://example.com/products/6',
 'czarny', 'męskie', 'zimowe', false, 'zimowe'),

('Buty trailowe Run Terrain',
 'Męskie buty trailowe do biegania w terenie z dobrą przyczepnością i lekką konstrukcją.',
 'Obuwie trailowe',
 259.99, 4.5, 110, 'https://example.com/products/7',
 'niebieski', 'męskie', 'trailowe', false, 'całoroczne'),

('Sandały trekkingowe Summer Path',
 'Sandały trekkingowe unisex do letnich spacerów i łatwych szlaków turystycznych.',
 'Sandały trekkingowe',
 159.99, 4.2, 74, 'https://example.com/products/8',
 'brązowy', 'unisex', 'sandały', false, 'letnie'),

('Buty miejskie Daily Walk',
 'Wygodne beżowe buty miejskie unisex do codziennego użytkowania i spacerów po mieście.',
 'Obuwie miejskie',
 199.99, 4.4, 132, 'https://example.com/products/9',
 'beżowy', 'unisex', 'sneakersy', false, 'całoroczne'),

('Buty robocze Safety Strong',
 'Wytrzymałe męskie buty robocze ze wzmocnionym noskiem i antypoślizgową podeszwą.',
 'Obuwie robocze',
 239.99, 4.3, 156, 'https://example.com/products/10',
 'czarny', 'męskie', 'robocze', false, 'całoroczne'),

('Czarne szpilki Evening Date',
 'Eleganckie czarne damskie szpilki na randkę, wieczorne wyjście i formalne okazje.',
 'Obuwie eleganckie damskie',
 219.99, 4.6, 98, 'https://example.com/products/11',
 'czarny', 'damskie', 'szpilki', false, 'całoroczne'),

('Czerwone szpilki Party Glam',
 'Czerwone damskie szpilki na imprezę, randkę i wieczorne stylizacje.',
 'Obuwie eleganckie damskie',
 249.99, 4.5, 76, 'https://example.com/products/12',
 'czerwony', 'damskie', 'szpilki', false, 'całoroczne'),

('Beżowe czółenka Office Comfort',
 'Beżowe damskie czółenka na niskim obcasie do pracy, biura i eleganckich stylizacji.',
 'Obuwie eleganckie damskie',
 199.99, 4.4, 84, 'https://example.com/products/13',
 'beżowy', 'damskie', 'czółenka', false, 'całoroczne'),

('Czarne botki Autumn Walk',
 'Czarne damskie botki na jesień, codzienne spacery i miejskie stylizacje.',
 'Botki damskie',
 269.99, 4.5, 112, 'https://example.com/products/14',
 'czarny', 'damskie', 'botki', false, 'jesienne'),

('Brązowe botki City Classic',
 'Brązowe damskie botki do miasta, pracy i codziennego chodzenia.',
 'Botki damskie',
 259.99, 4.3, 69, 'https://example.com/products/15',
 'brązowy', 'damskie', 'botki', false, 'jesienne'),

('Kozaki Winter Lady',
 'Czarne damskie kozaki zimowe z ociepleniem do chodzenia w niskich temperaturach.',
 'Kozaki damskie',
 329.99, 4.6, 91, 'https://example.com/products/16',
 'czarny', 'damskie', 'kozaki', false, 'zimowe'),

('Białe sneakersy Urban White',
 'Białe sneakersy unisex do codziennego chodzenia, miasta i casualowych stylizacji.',
 'Sneakersy',
 229.99, 4.7, 203, 'https://example.com/products/17',
 'biały', 'unisex', 'sneakersy', false, 'całoroczne'),

('Czarne sneakersy Street Black',
 'Czarne sneakersy unisex do miasta, codziennego użytkowania i luźnych stylizacji.',
 'Sneakersy',
 219.99, 4.5, 166, 'https://example.com/products/18',
 'czarny', 'unisex', 'sneakersy', false, 'całoroczne'),

('Niebieskie buty do biegania Speed Run',
 'Niebieskie męskie buty do biegania po asfalcie, treningu i aktywności sportowej.',
 'Obuwie biegowe',
 279.99, 4.6, 145, 'https://example.com/products/19',
 'niebieski', 'męskie', 'biegowe', false, 'całoroczne'),

('Damskie buty do biegania Light Run',
 'Lekkie damskie buty do biegania i treningu z miękką amortyzacją.',
 'Obuwie biegowe',
 249.99, 4.4, 118, 'https://example.com/products/20',
 'różowy', 'damskie', 'biegowe', false, 'całoroczne'),

('Czarne półbuty Business Man',
 'Czarne męskie półbuty eleganckie do garnituru, pracy i spotkań biznesowych.',
 'Obuwie eleganckie męskie',
 379.99, 4.6, 73, 'https://example.com/products/21',
 'czarny', 'męskie', 'półbuty', false, 'całoroczne'),

('Brązowe półbuty Smart Casual',
 'Brązowe męskie półbuty do pracy, randki i stylizacji smart casual.',
 'Obuwie eleganckie męskie',
 339.99, 4.4, 64, 'https://example.com/products/22',
 'brązowy', 'męskie', 'półbuty', false, 'całoroczne'),

('Wodoodporne buty trekkingowe Lady Mountain',
 'Damskie wodoodporne buty trekkingowe z membraną do chodzenia po górach i szlakach.',
 'Obuwie trekkingowe damskie',
 319.99, 4.8, 137, 'https://example.com/products/23',
 'szary', 'damskie', 'trekkingowe', true, 'całoroczne'),

('Męskie buty trekkingowe High Peak',
 'Męskie wysokie buty trekkingowe do gór, długich wędrówek i trudniejszego terenu.',
 'Obuwie trekkingowe męskie',
 389.99, 4.7, 126, 'https://example.com/products/24',
 'brązowy', 'męskie', 'trekkingowe', false, 'całoroczne'),

('Damskie sandały Summer Beige',
 'Beżowe damskie sandały letnie do sukienki, spacerów i codziennego chodzenia.',
 'Sandały damskie',
 149.99, 4.3, 82, 'https://example.com/products/25',
 'beżowy', 'damskie', 'sandały', false, 'letnie'),

('Męskie sandały Outdoor Air',
 'Męskie sandały outdoorowe na lato, spacer i lekkie szlaki.',
 'Sandały męskie',
 169.99, 4.2, 77, 'https://example.com/products/26',
 'czarny', 'męskie', 'sandały', false, 'letnie'),

('Białe trampki Classic Low',
 'Białe trampki unisex do codziennych stylizacji, miasta i szkoły.',
 'Trampki',
 129.99, 4.5, 211, 'https://example.com/products/27',
 'biały', 'unisex', 'trampki', false, 'letnie'),

('Czarne trampki Canvas Street',
 'Czarne trampki unisex do miasta, casualowych stylizacji i codziennego chodzenia.',
 'Trampki',
 139.99, 4.4, 178, 'https://example.com/products/28',
 'czarny', 'unisex', 'trampki', false, 'letnie'),

('Wodoodporne kalosze damskie Rain Lady',
 'Damskie kalosze wodoodporne na deszcz, błoto i spacer po mokrym terenie.',
 'Kalosze damskie',
 139.99, 4.3, 95, 'https://example.com/products/29',
 'czarny', 'damskie', 'kalosze', true, 'jesienne'),

('Wodoodporne kalosze męskie Field Rain',
 'Męskie kalosze wodoodporne do ogrodu, pracy w terenie, deszczu i błota.',
 'Kalosze męskie',
 149.99, 4.2, 89, 'https://example.com/products/30',
 'zielony', 'męskie', 'kalosze', true, 'jesienne');